name: 'Netlify Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          node-version: 12.x
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn
          restore-keys: ${{ runner.os }}-yarn

      - name: yarn install
        run: yarn install

      - name: testing
        run: |
          yarn lint
          yarn test:ci

      - name: Dist build
        run: |
          yarn dist
          yarn export

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy -p -d ./dist

      - name: Post Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_USERNAME: Deploy | "${{ secrets.PROJECT_NAME }}"
          SLACK_ICON: https://github.com/koenverburg.png?size=48
          SLACK_TITLE: ':rocket:New deployment:rocket:'
          SLACK_MESSAGE: "It's live on: ${{ secrets.PROJECT_DOMAIN }}"
